name: Snippet Manager
on:
  push:
    branches: [ "main" ]
  pull_request:
jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Backend Build & Run Tests
        working-directory: snippet-manager-back
        run: |
          chmod +x mvnw
          ./mvnw clean test package

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: snippet-manager-front/package-lock.json

      - name: Prepare Dependencies
        working-directory: snippet-manager-front
        run: npm ci

      - name: Frontend Tests
        working-directory: snippet-manager-front
        run: npm run test

      - name: Frontend Build
        working-directory: snippet-manager-front
        run: npm run build

  build-docker:
    needs: [build-backend, build-frontend]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Frontend Build Docker
        working-directory: snippet-manager-front
        run: docker build -t snippet-manager-frontend:1.1 .

      - name: Backend Build Docker
        working-directory: snippet-manager-back
        run: docker build -t snippet-manager-backend:1.0 .

      - name: List images
        run: docker images
